# server {
#     listen 443 ssl;
#     server_name as.wronamichal.online;
#
#     ssl_certificate /etc/certs/fullchain.pem;
#     ssl_certificate_key /etc/certs/privkey.pem;
#
#     location / {
#         proxy_pass http://studify-backend:8080;
#
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto https;
#
#         proxy_redirect off;
#     }
# }

server {
    listen 80;
    listen [::]:80;
    server_name as.wronamichal.online;

    add_header X-Robots-Tag "noindex, nofollow" always;

    location / {
        add_header X-Robots-Tag "noindex, nofollow" always;

        proxy_pass http://studify-backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name new-vision.wronamichal.online;

    root /var/www/newvision;
    index index.html;
    charset utf-8;

    access_log /var/log/nginx/new-vision.access.log;
    error_log /var/log/nginx/new-vision.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js|svg|png|jpe?g|webp|ico|woff2?)$ {
        try_files $uri =404;
        expires 7d;
    }

    location ~ /\. {
        deny all;
    }

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/css application/javascript image/svg+xml;
}